# 🎨 Analysis

This notebook analysis the experimental results from training a digital-to-film style transfer model. It uses the experiment results that are tracked to W&B during training from the `scr/train.py` script.

## Setup

---

Let's install some necessary dependencies and set global variables.

In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import autorootcwd

In [3]:
# Imports
import wandb

import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [4]:
# Constants
WANDB_PROJECT = "sillystill"
WANDB_ENTITY = "sillystill"

## Connect to W&B

---

Let's start by loading all the runs from the W&B project.

In [5]:
# Initialize W&B
api = wandb.Api()

# Get runs
runs = api.runs(f"{WANDB_ENTITY}/{WANDB_PROJECT}")
print(f"✅ Loaded {len(runs)} runs from W&B ({WANDB_ENTITY}/{WANDB_PROJECT})")

✅ Loaded 279 runs from W&B (sillystill/sillystill)

## Experiment 1: Single Image

---

In [6]:
def load_results(path, runs):
    data = pd.read_csv(path)

    baselines_cols = ["baseline_lpips", "baseline_psnr", "baseline_ssim", "baseline_pieapp"]
    baselines = data.iloc[0][baselines_cols].rename(lambda x: x.replace("baseline_", ""), axis=0)

    # Remove baseline cols  + media col
    data = data.drop(columns=["digitalfilepath", "filmfilepath", "predictedfilepath"])
    data = data.drop(columns=["baseline_lpips", "baseline_psnr", "baseline_ssim", "baseline_pieapp"])

    # Retrieve other runs from api
    runs = [run for run in runs if run.name in data["run_name"].unique()]

    tags = [" - ".join(set(run.tags) - set(["Combined"])) for run in runs]
    with_noise = [run.config["model"]["net"]["with_noise"] for run in runs]
    data["tags"] = tags
    data["with_noise"] = with_noise

    # Add baseline
    idx = len(data)
    data.loc[idx] = baselines
    data.loc[idx, "run_name"] = "baseline"
    data.loc[idx, "tags"] = "Baseline"
    
    return data

### Simple Losses

In [7]:
# W/o noise
single_image = load_results("outputs/single-image.csv", runs)
single_image

,run_name,lpips,pieapp,psnr,ssim,tags,with_noise
0,lucky-hill-641,0.302564,1.871027,18.612707,0.665786,MSE - Resized,1.0
1,sparkling-armadillo-640,0.345288,2.822251,19.922535,0.655083,MSE - Resized - VGG,1.0
2,woven-tree-639,0.351533,1.621794,23.187956,0.706527,MSE - Resized - VGG,0.0
3,resilient-haze-638,0.471837,1.771875,20.031443,0.672145,MSE - Resized,0.0
4,celestial-jazz-627,0.465535,3.468067,18.305382,0.653564,MSE - TV-Rel - VGG,0.0
5,lively-violet-626,0.446268,1.417452,19.668020,0.680469,Color - TV-Rel - VGG,0.0
6,fallen-flower-625,0.448161,1.612100,20.074440,0.677798,Color - VGG,0.0
7,grateful-darkness-624,0.475350,2.530893,18.260416,0.655955,MSE - VGG,0.0
8,youthful-smoke-623,0.366658,1.141011,18.010405,0.673318,Color - TV-Rel - VGG,1.0
9,splendid-bird-622,0.301898,1.837799,20.135492,0.661510,MSE - TV-Rel - VGG,1.0
10,stellar-fog-621,0.363042,1.583529,17.944693,0.677025,Color - VGG,1.0
11,grateful-deluge-620,0.337840,2.047208,19.786139,0.670784,MSE - VGG,1.0
12,electric-pond-619,0.268534,2.201179,11.113188,0.267985,TV-Rel,1.0
13,eager-puddle-618,0.600216,19.050661,4.957153,0.002744,TV-Abs,1.0
14,glad-oath-617,0.426483,2.498248,15.661246,0.630099,Color,1.0
15,fresh-oath-616,0.640356,5.112303,8.713161,0.057539,VGG,1.0
16,unique-durian-615,0.317415,1.886814,19.255795,0.671745,MSE,1.0
17,rare-plant-614,0.330563,1.958885,19.035898,0.681236,MAE,1.0
18,fine-cosmos-613,0.602377,4.837533,9.837147,0.170945,TV-Rel,0.0
19,vocal-haze-612,0.526335,19.049109,4.957157,0.002699,TV-Abs,0.0
20,dry-spaceship-611,0.504249,2.988388,18.449396,0.650052,Color,0.0
21,devout-night-609,0.619815,4.504423,9.095779,0.160450,VGG,0.0
22,stoic-haze-608,0.503105,2.115091,18.609236,0.652234,MAE,0.0
23,confused-voice-607,0.499604,2.420474,18.285091,0.646375,MSE,0.0
24,baseline,0.360336,3.788267,16.973549,0.641226,Baseline,NaN

In [8]:
# Find mean and std for each metric
single_image.groupby(["run_name", "tags", "with_noise"]).agg(
    {"lpips": ["mean"],
     "psnr": ["mean"],
     "ssim": ["mean"],
     "pieapp": ["mean"]}).sort_values(by=("ssim", "mean"), ascending=False)

,,,lpips,psnr,ssim,pieapp
,,,mean,mean,mean,mean
run_name,tags,with_noise,,,,
woven-tree-639,MSE - Resized - VGG,0.0,0.351533,23.187956,0.706527,1.621794
rare-plant-614,MAE,1.0,0.330563,19.035898,0.681236,1.958885
lively-violet-626,Color - TV-Rel - VGG,0.0,0.446268,19.668020,0.680469,1.417452
fallen-flower-625,Color - VGG,0.0,0.448161,20.074440,0.677798,1.612100
stellar-fog-621,Color - VGG,1.0,0.363042,17.944693,0.677025,1.583529
youthful-smoke-623,Color - TV-Rel - VGG,1.0,0.366658,18.010405,0.673318,1.141011
resilient-haze-638,MSE - Resized,0.0,0.471837,20.031443,0.672145,1.771875
unique-durian-615,MSE,1.0,0.317415,19.255795,0.671745,1.886814
grateful-deluge-620,MSE - VGG,1.0,0.337840,19.786139,0.670784,2.047208
lucky-hill-641,MSE - Resized,1.0,0.302564,18.612707,0.665786,1.871027
splendid-bird-622,MSE - TV-Rel - VGG,1.0,0.301898,20.135492,0.661510,1.837799
grateful-darkness-624,MSE - VGG,0.0,0.475350,18.260416,0.655955,2.530893
sparkling-armadillo-640,MSE - Resized - VGG,1.0,0.345288,19.922535,0.655083,2.822251
celestial-jazz-627,MSE - TV-Rel - VGG,0.0,0.465535,18.305382,0.653564,3.468067
stoic-haze-608,MAE,0.0,0.503105,18.609236,0.652234,2.115091
dry-spaceship-611,Color,0.0,0.504249,18.449396,0.650052,2.988388
confused-voice-607,MSE,0.0,0.499604,18.285091,0.646375,2.420474
glad-oath-617,Color,1.0,0.426483,15.661246,0.630099,2.498248
electric-pond-619,TV-Rel,1.0,0.268534,11.113188,0.267985,2.201179
fine-cosmos-613,TV-Rel,0.0,0.602377,9.837147,0.170945,4.837533
devout-night-609,VGG,0.0,0.619815,9.095779,0.160450,4.504423
fresh-oath-616,VGG,1.0,0.640356,8.713161,0.057539,5.112303
eager-puddle-618,TV-Abs,1.0,0.600216,4.957153,0.002744,19.050661
vocal-haze-612,TV-Abs,0.0,0.526335,4.957157,0.002699,19.049109

In [9]:
# TODO: Do some plotting here

# Probably useful to pivot the data
# single_image.melt(id_vars=["run_name", "tags", "with_noise"], var_name="metric", value_name="value")

## Experiment 2: Full Data

---

In [10]:
def load_results(path, runs):
    data = pd.read_csv(path)

    data = data.drop(columns=["digitalfilepath", "filmfilepath", "predictedfilepath"])

    # Make index from 1-37 replicated num_runs times
    idx = list(range(1, 38)) * data.run_name.nunique()
    data["image_idx"] = idx

    # Add run names
    runs = [run for run in runs if run.name in data["run_name"].unique()]
    tags = pd.Series([" - ".join(set(run.tags) - set(["Combined"])) for run in runs]).repeat(37).reset_index(drop=True)
    with_noise = pd.Series([run.config["model"]["net"]["with_noise"] for run in runs]).repeat(37).reset_index(drop=True)
    data["tags"] = tags
    data["with_noise"] = with_noise

    # Grab baselines
    baselines_cols = ["baseline_lpips", "baseline_psnr", "baseline_ssim", "baseline_pieapp"]
    baselines = data.iloc[:37, 5:-1].rename(lambda x: x.replace("baseline_", ""), axis=1)
    baselines["image_idx"] = idx[:37]
    baselines["run_name"] = "baseline"
    baselines["tags"] = "Baseline"
    baselines["with_noise"] = False
    data = data.drop(columns=baselines_cols)

    return pd.concat([data, baselines], axis=0)

In [11]:
full_data = load_results("outputs/full-data.csv", runs)
full_data

,run_name,lpips,pieapp,psnr,ssim,image_idx,tags,with_noise
0,zany-sun-643,0.360297,3.297302,22.774420,0.553874,1,MSE - Resized,True
1,zany-sun-643,0.370834,2.762157,25.020437,0.547328,2,MSE - Resized,True
2,zany-sun-643,0.347532,3.422191,20.254227,0.603162,3,MSE - Resized,True
3,zany-sun-643,0.287149,2.837529,20.418079,0.408775,4,MSE - Resized,True
4,zany-sun-643,0.361073,3.700911,20.807051,0.412589,5,MSE - Resized,True
...,...,...,...,...,...,...,...,...
32,baseline,0.294222,1.832007,21.575945,0.656677,33,Baseline,False
33,baseline,0.229794,1.643022,21.897480,0.689344,34,Baseline,False
34,baseline,0.318293,5.393808,17.782415,0.630673,35,Baseline,False
35,baseline,0.255709,1.344045,18.154837,0.580547,36,Baseline,False
36,baseline,0.452504,1.551278,23.559841,0.484367,37,Baseline,False

In [12]:
# Find mean and std for each metric
full_data.groupby(["run_name", "tags", "with_noise"]).agg(
    {"lpips": ["mean", "std"],
     "psnr": ["mean", "std"],
     "ssim": ["mean", "std"],
     "pieapp": ["mean", "std"]}).sort_values(by=("ssim", "mean"), ascending=False)

                                                      lpips            \
                                                       mean       std
run_name           tags                with_noise
baseline           Baseline            False       0.262064  0.068482
balmy-lion-642     MSE - Resized - VGG True        0.268183  0.073839
colorful-tree-637  MSE - Resized - VGG False       0.274965  0.074144
leafy-snowball-635 MSE - Resized       False       0.353089  0.073014
zany-sun-643       MSE - Resized       True        0.404321  0.068639
lunar-sea-630      MAE                 False       0.481269  0.082440
curious-sound-631  MSE                 False       0.501516  0.084464
eager-glade-633    MSE - VGG           False       0.483725  0.067783

                                                        psnr            \
                                                        mean       std
run_name           tags                with_noise
baseline           Baseline            False       21.681033  2.015000
balmy-lion-642     MSE - Resized - VGG True        22.874450  2.201512
colorful-tree-637  MSE - Resized - VGG False       22.847087  2.161391
leafy-snowball-635 MSE - Resized       False       22.201927  2.148667
zany-sun-643       MSE - Resized       True        20.866321  2.390402
lunar-sea-630      MAE                 False       19.686195  2.282185
curious-sound-631  MSE                 False       20.473758  2.157028
eager-glade-633    MSE - VGG           False       20.713680  2.083411

                                                       ssim            \
                                                       mean       std
run_name           tags                with_noise
baseline           Baseline            False       0.640369  0.088424
balmy-lion-642     MSE - Resized - VGG True        0.636272  0.096435
colorful-tree-637  MSE - Resized - VGG False       0.634165  0.099041
leafy-snowball-635 MSE - Resized       False       0.629131  0.088538
zany-sun-643       MSE - Resized       True        0.589608  0.088115
lunar-sea-630      MAE                 False       0.589580  0.086748
curious-sound-631  MSE                 False       0.579717  0.097619
eager-glade-633    MSE - VGG           False       0.576729  0.107985

                                                     pieapp
                                                       mean       std
run_name           tags                with_noise
baseline           Baseline            False       1.956504  0.828218
balmy-lion-642     MSE - Resized - VGG True        1.896412  0.621433
colorful-tree-637  MSE - Resized - VGG False       1.843136  0.588871
leafy-snowball-635 MSE - Resized       False       2.313303  0.738792
zany-sun-643       MSE - Resized       True        3.293952  0.853512
lunar-sea-630      MAE                 False       3.379237  0.673081
curious-sound-631  MSE                 False       3.668625  0.876797
eager-glade-633    MSE - VGG           False       3.488364  0.940559

In [13]:
# TODO: Do some plotting here

# Probably useful to pivot the data
# full_data.melt(id_vars=["run_name", "tags", "with_noise"], var_name="metric", value_name="value")